# Generated by Django 3.1.7 on 2021-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210303_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'الملف الشخصي', 'verbose_name_plural': 'الملفات الشخصية'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'المستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
