# Generated by Django 3.1.7 on 2021-03-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210303_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../static/img/profile.png', null=True, upload_to='profile/'),
        ),
    ]
