# Generated by Django 3.1.7 on 2021-03-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_contact_content_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='about_us_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='header_description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
