# Generated by Django 3.1.7 on 2021-03-04 09:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20210304_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firsrt_email',
            new_name='first_email',
        ),
        migrations.AlterField(
            model_name='content',
            name='about_us_description',
            field=ckeditor.fields.RichTextField(default='info@mulvice.org'),
            preserve_default=False,
        ),
    ]
