# Generated by Django 3.1.7 on 2021-03-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20210304_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='../static/img/photo1.jpg', upload_to='videos/'),
        ),
    ]
