# Generated by Django 3.1.7 on 2021-03-05 16:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_auto_20210304_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'التواصل', 'verbose_name_plural': 'إعدادات معلومات الاتصال'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'المحتوى', 'verbose_name_plural': 'إعدادات المتحويات'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'فيديو', 'verbose_name_plural': 'الفيديوهات'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='adresse',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الفيسبوك'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الإيميل الأول'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الانستغرام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secound_email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الإيميل الثاني'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='تويتر'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtube',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='يوتوب'),
        ),
        migrations.AlterField(
            model_name='content',
            name='about_us_description',
            field=ckeditor.fields.RichTextField(verbose_name='وصف صفحة من نحن'),
        ),
        migrations.AlterField(
            model_name='content',
            name='about_us_image',
            field=models.ImageField(default='../static/img/photo1.jpg', upload_to='images/', verbose_name='صورة صفحة من نحن'),
        ),
        migrations.AlterField(
            model_name='content',
            name='about_us_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان صفحة من نحن'),
        ),
        migrations.AlterField(
            model_name='content',
            name='blog_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان قسم المقالات'),
        ),
        migrations.AlterField(
            model_name='content',
            name='favicon',
            field=models.ImageField(default='../static/img/photo1.jpg', upload_to='images/', verbose_name='صورة أيقونة الشعار'),
        ),
        migrations.AlterField(
            model_name='content',
            name='header_description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='وصف رأس الصفحة'),
        ),
        migrations.AlterField(
            model_name='content',
            name='header_image',
            field=models.ImageField(default='../static/img/photo1.jpg', upload_to='images/', verbose_name='صورة رأص الصفحة'),
        ),
        migrations.AlterField(
            model_name='content',
            name='header_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان رأس الصفحة'),
        ),
        migrations.AlterField(
            model_name='content',
            name='logo',
            field=models.ImageField(default='../static/img/photo1.jpg', upload_to='images/', verbose_name='صورة الشعار'),
        ),
        migrations.AlterField(
            model_name='content',
            name='videos_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان قسم الفيديوهات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='مسؤول'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='عامل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='اللقب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الإسم'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(default='../static/img/photo1.jpg', upload_to='videos/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان URL'),
        ),
    ]
