# Generated by Django 3.1.7 on 2021-03-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20210305_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='header_description_s',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='وصف رأس الصفحة الثاني'),
        ),
        migrations.AddField(
            model_name='content',
            name='header_image_s',
            field=models.ImageField(default='../static/img/photo1.jpg', upload_to='images/', verbose_name='صورة رأ الثانيةص الصفحة'),
        ),
        migrations.AddField(
            model_name='content',
            name='header_title_s',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان رأس الصفحة الثاني'),
        ),
    ]
