# Generated by Django 3.1.7 on 2021-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_auto_20210305_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='رقم عميل PayPal'),
        ),
    ]
