# Generated by Django 3.1.7 on 2021-03-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_content_paypal_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='og_image',
            field=models.ImageField(default='../static/img/photo1.jpg', upload_to='images/', verbose_name='صورة الوصف'),
        ),
        migrations.AddField(
            model_name='content',
            name='subscribe_text',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='محتوى إشترك معنا'),
        ),
        migrations.AddField(
            model_name='content',
            name='subscribe_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='رابط إشترك معنا'),
        ),
        migrations.AddField(
            model_name='content',
            name='website_description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='وصف الموقع '),
        ),
    ]
