# Generated by Django 3.1.7 on 2021-04-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_content_logo_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='training_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان  قسم  الدورات'),
        ),
    ]
