# Generated by Django 3.1.7 on 2021-03-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'ﺔﺌﻔﻟا', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'مقال', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='statut',
            field=models.IntegerField(choices=[(0, 'مسودة'), (1, 'ينشر')], default=0),
        ),
    ]
