# Generated by Django 3.1.7 on 2021-03-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20210302_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='شمهسيعباش شسهيبشسيب شحسيعهباشسيب'),
            preserve_default=False,
        ),
    ]
