# Generated by Django 3.1.7 on 2021-03-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20210304_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nb_posts',
            field=models.IntegerField(default=0, verbose_name='عدد المقالات'),
        ),
    ]
