# Generated by Django 3.1.7 on 2021-03-07 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Training', '0002_auto_20210307_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Training.training'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'training')},
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
    ]
