# Generated by Django 3.1.7 on 2021-03-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0004_auto_20210307_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='training',
            name='nb_purchase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Training.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='training',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Training.training'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
