# Generated by Django 3.1.7 on 2021-03-08 12:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Training', '0005_auto_20210308_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'الدرس', 'verbose_name_plural': 'الدروس'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'الوحدة', 'verbose_name_plural': 'الوحدات'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-created_on'], 'verbose_name': 'دورة', 'verbose_name_plural': 'الدورات'},
        ),
        migrations.AlterModelOptions(
            name='usertraining',
            options={'verbose_name': 'دورة', 'verbose_name_plural': 'الدورات'},
        ),
        migrations.AddField(
            model_name='training',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training.section', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان الدرس'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عنوان الوحدة'),
        ),
        migrations.AlterField(
            model_name='section',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training.training', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='training',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='training',
            name='nb_purchase',
            field=models.IntegerField(default=0, verbose_name='عدد المشتريات'),
        ),
        migrations.AlterField(
            model_name='training',
            name='price',
            field=models.FloatField(default=0, verbose_name='الثمن'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عنوان الدورة'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الشراء'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Training.training', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
