# Generated by Django 3.1.7 on 2021-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0008_auto_20210308_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتيب الدرس'),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتيب الوحدة'),
        ),
    ]
