# Generated by Django 3.1.7 on 2021-03-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0011_auto_20210316_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='الوصف'),
        ),
    ]
