# Generated by Django 3.1.7 on 2021-03-17 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Training', '0012_training_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Training.training', verbose_name='الدورة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Accounts.user', verbose_name='المستخدم'),
            preserve_default=False,
        ),
    ]
