# Generated by Django 3.1.7 on 2021-03-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0014_course_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='price_dzd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الثمن'),
        ),
        migrations.AlterField(
            model_name='course',
            name='opened',
            field=models.BooleanField(default=False, verbose_name='درس مفتوح'),
        ),
    ]
