# Generated by Django 3.1.7 on 2021-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0015_auto_20210325_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='statut',
            field=models.IntegerField(choices=[(0, 'مسودة'), (1, 'ينشر')], default=1, verbose_name='الحالة'),
        ),
    ]
